# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Thq7YtS--2os3fYGWCgBsTQKRAug3aDN
"""

!pip install requests beautifulsoup4

# Install required libraries
!pip install requests beautifulsoup4 pandas

import requests
from bs4 import BeautifulSoup
import pandas as pd

# List of article URLs to scrape
urls = [
    "https://www.verywellmind.com/what-is-anxiety-2795454",
    "https://www.verywellmind.com/what-is-depression-2795029",
    "https://www.verywellmind.com/what-is-cognitive-behavioral-therapy-2795747",
    "https://www.verywellmind.com/tips-to-reduce-stress-3145195"
]

all_paragraphs = []

# Loop through URLs and extract paragraph texts
for url in urls:
    print(f"Scraping: {url}")
    try:
        response = requests.get(url, headers={"User-Agent": "Mozilla/5.0"})
        soup = BeautifulSoup(response.text, 'html.parser')
        paragraphs = soup.find_all('p')
        text_data = [p.get_text().strip() for p in paragraphs if len(p.get_text().strip()) > 30]
        all_paragraphs.extend(text_data)
    except Exception as e:
        print(f"Error scraping {url}: {e}")

# Save all extracted paragraphs to a CSV file
df = pd.DataFrame(all_paragraphs, columns=['paragraph'])
df.to_csv('mental_health_data.csv', index=False, encoding='utf-8')

print(f"✅ Done! Collected {len(all_paragraphs)} paragraphs.")

from google.colab import files
files.download('mental_health_data.csv')

import pandas as pd
import re

# Load the collected data
df = pd.read_csv("mental_health_data.csv")

# Combine all paragraphs into one long string
full_text = ' '.join(df['paragraph'].dropna().tolist())

# Clean the text (remove extra spaces, special symbols, etc.)
cleaned_text = re.sub(r'\s+', ' ', full_text)  # remove newlines, tabs, etc.
cleaned_text = re.sub(r'[^a-zA-Z0-9.,;:!?()\s]', '', cleaned_text)  # keep letters, numbers & punctuation

# Split into words
words = cleaned_text.split()

# Split into chunks of ~400 words
chunk_size = 400
chunks = []

for i in range(0, len(words), chunk_size):
    chunk = ' '.join(words[i:i+chunk_size])
    if len(chunk.split()) >= 200:  # make sure chunk has at least 200 words
        chunks.append(chunk)

# Save the chunks in a new CSV
chunk_df = pd.DataFrame(chunks, columns=["chunk"])
chunk_df.to_csv("cleaned_chunks.csv", index=False, encoding="utf-8")

print(f"✅ Done! Saved {len(chunks)} chunks.")

from google.colab import files
files.download("cleaned_chunks.csv")

!pip install -U sentence-transformers

from sentence_transformers import SentenceTransformer
import pandas as pd
import numpy as np

# Load cleaned chunks
df = pd.read_csv("cleaned_chunks.csv")

# Load the embedding model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Apply model to all text chunks
embeddings = model.encode(df['chunk'].tolist(), show_progress_bar=True)

# Convert to numpy array and save
np.save("chunk_embeddings.npy", embeddings)

print(f"✅ Embedding complete! Saved embeddings for {len(embeddings)} chunks.")

from google.colab import files
files.download("chunk_embeddings.npy")

!pip install faiss-cpu

import faiss
import numpy as np
import pandas as pd

# Load the embeddings and the corresponding chunks
embeddings = np.load("chunk_embeddings.npy")
df_chunks = pd.read_csv("cleaned_chunks.csv")

# Define the dimensionality of vectors
dimension = embeddings.shape[1]

# Create FAISS index
index = faiss.IndexFlatL2(dimension)
index.add(embeddings)

# Save index and text together (for retrieval later)
faiss.write_index(index, "faiss_index.index")
df_chunks.to_csv("indexed_chunks.csv", index=False)

print(f"✅ FAISS index created and saved! Total chunks indexed: {len(embeddings)}")

from google.colab import files
files.download("faiss_index.index")
files.download("indexed_chunks.csv")

!pip install sentence-transformers faiss-cpu transformers

import faiss
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

# Load FAISS index and chunks
index = faiss.read_index("faiss_index.index")
df_chunks = pd.read_csv("indexed_chunks.csv")

# Load embedding model
embed_model = SentenceTransformer('all-MiniLM-L6-v2')

# Load Hugging Face language model (DistilGPT2 or small model for demo)
tokenizer = AutoTokenizer.from_pretrained("distilgpt2")
model = AutoModelForCausalLM.from_pretrained("distilgpt2")

# Function to answer questions
def ask_question_rag(question, top_k=3):
    # Embed the question
    q_embedding = embed_model.encode([question])

    # Search in FAISS index
    D, I = index.search(q_embedding, top_k)

    # Get top matching chunks
    retrieved_chunks = df_chunks.iloc[I[0]]['chunk'].tolist()
    context = "\n\n".join(retrieved_chunks)

    # Create prompt
    prompt = f"""You are a mental health assistant. Use the following context to answer the user's question.

Context:
{context}

Question: {question}
Answer:"""

    # Tokenize input
    inputs = tokenizer.encode(prompt, return_tensors="pt", max_length=1024, truncation=True)

    # Generate response
    outputs = model.generate(inputs, max_new_tokens=150, do_sample=True, temperature=0.7)
    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return answer.split("Answer:")[-1].strip()

# Example usage
print(ask_question_rag("What is cognitive behavioral therapy?"))

!pip install streamlit



